steps:
- bash: mkdir -pv ./gopath/src/github.com/mweagle/helloworld
  displayName: Initialize source directory

- bash: |
    for EACHFILE in $(ls .);
    do if [ $EACHFILE != "gopath" ];
      then mv -v $EACHFILE ./gopath/src/github.com/mweagle/helloworld/$EACHFILE;
    fi;
    done
  displayName: Move source

- bash: curl -L -O https://dl.google.com/go/go1.9.2.linux-amd64.tar.gz
  displayName: Download Go

- bash: tar -xzf go1.9.2.linux-amd64.tar.gz
  displayName: Expand Go

- bash: go build
  workingDirectory: ./gopath/src/github.com/mweagle/helloworld
  env:
    GOROOT: $AGENT_WORKFOLDER/go
    GOPATH: $AGENT_WORKFOLDER/gopath
    PATH: $PATH:$AGENT_WORKFOLDER/go/bin
  displayName: Build
