steps:
- bash: mkdir -pv ./gopath/src/github.com/mweagle/helloworld
  displayName: Initialize source directory

- bash: mv  -v ./* ./gopath/src/github.com/mweagle/helloworld
  displayName: Move source

- bash: curl -L -O https://dl.google.com/go/go1.9.2.linux-amd64.tar.gz
  displayName: Download Go

- bash: tar -xzvf go1.9.2.linux-amd64.tar.gz
  displayName: Expand Go

- bash: go build
  workingDirectory: ./gopath/src/github.com/mweagle/helloworld
  env:
    GOROOT: ./go
    GOPATH: ./gopath
  displayName: Build
